/**
 * Core primitives for the ZK-PRU attack simulation suite.
 *
 * Real: wallet keys are genuine Ed25519 keypairs generated by Node's
 * built-in crypto module. Signing and verification use real asymmetric
 * cryptography. This matches the Solana wallet model used by ZK-PRU.
 *
 * Simulated: the suite uses SHA-256 as a stand-in hash chain so it can
 * run with zero external dependencies. The production derivation and
 * circuit path use Poseidon.
 */
import crypto from "node:crypto";

const RESET = "\x1b[0m";
const BOLD = "\x1b[1m";
const DIM = "\x1b[2m";
const RED = "\x1b[31m";
const GREEN = "\x1b[32m";
const YELLOW = "\x1b[33m";
const CYAN = "\x1b[36m";
const MAGENTA = "\x1b[35m";

export function section(title) {
  console.log("");
  console.log(`${BOLD}${CYAN}━━━ ${title} ━━━${RESET}`);
}

export function narrate(msg) {
  console.log(`${DIM}   ${msg}${RESET}`);
}

export function step(msg) {
  console.log(`   ${CYAN}→${RESET} ${msg}`);
}

export function info(label, value) {
  const stringValue = String(value);
  console.log(`   ${DIM}${label}:${RESET} ${stringValue.slice(0, 96)}${stringValue.length > 96 ? "…" : ""}`);
}

export function attackerGets(label, value) {
  const stringValue = String(value);
  console.log(`   ${YELLOW}⚡ attacker now has ${label}:${RESET} ${stringValue.slice(0, 96)}${stringValue.length > 96 ? "…" : ""}`);
}

export function defended(msg) {
  console.log(`   ${GREEN}${BOLD}✅ DEFENDED${RESET} — ${msg}`);
}

export function vulnerable(msg) {
  console.log(`   ${RED}${BOLD}❌ VULNERABLE${RESET} — ${msg}`);
}

export function critical(msg) {
  console.log(`   ${MAGENTA}${BOLD}⚠ CRITICAL (documented boundary, not a bug)${RESET} — ${msg}`);
}

export function generateWallet() {
  const { publicKey, privateKey } = crypto.generateKeyPairSync("ed25519");
  const pubDer = publicKey.export({ type: "spki", format: "der" });
  const address = "SolPub" + crypto.createHash("sha256").update(pubDer).digest("base64url").slice(0, 38);
  return { address, publicKey, privateKey };
}

export function sign(privateKey, message) {
  return crypto.sign(null, Buffer.from(message), privateKey).toString("hex");
}

export function verifySignature(publicKey, message, signatureHex) {
  try {
    return crypto.verify(null, Buffer.from(message), publicKey, Buffer.from(signatureHex, "hex"));
  } catch {
    return false;
  }
}

export function fieldHash(...inputs) {
  const h = crypto.createHash("sha256");
  for (const input of inputs) h.update(String(input));
  return h.digest("hex");
}

export function buildIdentityChallenge({ cluster, registryProgramId, version, walletPublicKey }) {
  return [
    "ZK-PRU Identity Root",
    `Cluster: ${cluster}`,
    `Registry Program: ${registryProgramId}`,
    `Wallet: ${walletPublicKey}`,
    `Version: ${version}`,
    "Purpose: identity_root",
  ].join("\n");
}

export function buildVaultChallenge({ cluster, registryProgramId, version, walletPublicKey }) {
  return [
    "ZK-PRU Vault Root",
    `Cluster: ${cluster}`,
    `Registry Program: ${registryProgramId}`,
    `Wallet: ${walletPublicKey}`,
    `Version: ${version}`,
    "Purpose: vault_root",
  ].join("\n");
}

export function deriveIdentitySeed(walletAddress, identitySignature) {
  return fieldHash("IDENTITY_SEED", walletAddress, identitySignature);
}

export function derivePRUSeed(identitySeed, contextId, vaultSignature) {
  return fieldHash("PRU_SEED", identitySeed, contextId, vaultSignature);
}

export function derivePRU(pruSeed, index) {
  return fieldHash("PRU", pruSeed, index);
}

export function deriveCommitment(pruSeed) {
  return fieldHash("COMMITMENT", pruSeed);
}

export function deriveActionCommitment(pruSeed, actionPayloadHash) {
  return fieldHash("ACTION", pruSeed, actionPayloadHash);
}
