/**
 * Shared type definitions for ZK-PRU.
 *
 * NEW SECURE ARCHITECTURE:
 * - masterSeed: Independently random 32 bytes, generated by CSPRNG. Never transmitted in plaintext.
 * - Private values are wrapped in branded types so they cannot be accidentally passed where public values are expected.
 * - The wallet's job is ONLY to encrypt/decrypt the master seed, not to derive it.
 */

/** A value that must never cross a network boundary or be persisted in plaintext. */
export type Private<T> = T & { readonly __private: true };

/** A value that is safe to publish in registry records, network calls, or logs. */
export type Public<T> = T & { readonly __public: true };

/** A 32-byte master seed generated by CSPRNG. The foundation of all PRU derivation. */
export type MasterSeed = Private<Uint8Array>;

/** AES-256-GCM encrypted master seed. Safe to store and transmit anywhere. */
export interface EncryptedSeed {
  ciphertext: string;   // Base64-encoded encrypted data
  iv: string;           // Base64-encoded initialization vector
  authTag: string;      // Base64-encoded authentication tag
}

/** Key derived from wallet signature for encrypting/decrypting master seed. */
export type VaultKey = Private<string>;

/** Salt for protocol-specific PRU derivation. */
export type ProtocolSalt = Private<string>;

export type FieldElement = bigint;

export type SolanaCluster = "devnet" | "testnet" | "mainnet-beta" | "localnet";

export interface RegistryBinding {
  cluster: SolanaCluster;
  registryProgramId: string;
  version: string;
}

export interface WalletSigner {
  publicKey: string;
  /** Must produce a deterministic signature for a given canonical message. */
  signMessage(message: Uint8Array): Promise<Uint8Array | string>;
}

/** Identity material for the new architecture: master seed + vault key. */
export interface IdentityMaterial {
  masterSeed: MasterSeed;
  vaultKey: VaultKey;
}

export interface PRUHandle {
  contextId: string;
  index: number;
  pru: Public<FieldElement>;
}

export interface RegistryRecord {
  pru: string;
  contextId: string;
  commitmentHash: string;
}

export interface ProofBundle {
  contextId: string;
  pru: Public<FieldElement>;
  proof: Uint8Array;
}

/**
 * Registry keyed by PRU, not by context_id. The context_id is shared by
 * every user of a protocol, while each PRU is unique.
 */
export interface Registry {
  register(contextId: string, pru: string, commitmentHash: string): Promise<void>;
  getRecord(pru: string): Promise<{ contextId: string; commitmentHash: string } | null>;
  getPRUsForContext(contextId: string): Promise<string[]>;
}

/** Mode B fallback must be explicitly requested. */
export interface AuthorizeOptions {
  allowFallback?: boolean;
}

/** Recovery challenge request - contains unique challenge that user must sign. */
export interface RecoveryChallenge {
  challenge: string;
  timestamp: number;
  expiresAt: number;
}

/** Encrypted seed blob for storage/recovery - stored in TIN account or personal vault. */
export interface SeedBlob {
  encryptedSeed: EncryptedSeed;
  ownerPubkeyHash: string;
  createdAt: number;
  version: string;
}
